### ISSUE TITLE
sth. about function and UI

### ISSUE THREAD

**Issue by jay-xjh** [hugsy/gef#1067]
### Type of feature request

None

### Summary Description

When I use gef for heap exploitation,I always have an annoyance that it is extremely inconvenient when I look at heap pointers.In the past when I used pwndbg I could just use $rebase,such as x/10gx $rebase(0x4060).But now with gef I can only look at the codebase first and then add the relative offset,it bothers me.A similar problem exists with stack overflow,maybe it's because I'm used to pwndbg, maybe not.I think pwndbg does a better job of typesetting context. It makes it easier for me to see what's going on in the stack.When I working with gef, it's easy to overlook stack changes.

### Implementation idea/suggestion

I hope that author can greatly combine gef and pwndbg organically, and integrate pwndbg's page layout and some nice functions.

### Existing alternatives?

pwndbg

**Comment by hugsy** [comment]
This issue is too vague, there's nothing actionable. Closing this.
GEF does use also convenience variables (like `$heap`, `$stack`, etc.) and it's very well documented.

@jay-xjh If you want something changed or added in GEF, open a proper issue with details of what exactly should be done (not just "something about function and ui"), how it would improve the current state, and if you're capable a suggestion of implementation. Also make sure you've read thoroughly the documentation before.

FWIW Saying "pwndbg does it differently" will never result in anything done.
