### ISSUE TITLE
heap bins incorrectly shows in use chunks in fast bin list

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#158]
since the fast bins don't unset the prev-inuse bit of the adjacent chunk, our heap chunk code sees it as inuse.

**Comment by Grazfather** [comment]
Will write a test after work.

**Comment by hugsy** [comment]
I thought about it, I don't think we shouldn't change it as this behaviour is assumed:
> Note - some chunks, such as those in fastbins (see below) will have this bit set despite being free'd by the application.
https://sourceware.org/glibc/wiki/MallocInternals

(i.e. it is not a error from gef nor the libc)

If the chunk is in the fastbins, it doesn't matter if `PREV_INUSE` is set and not showing it might be misleading during the exploit dev since you can easily [have cases](https://github.com/shellphish/how2heap/blob/master/fastbin_dup.c) where a chunk is used and is in fastbins. 

That being said, we should maybe make thing more transparent then, like explicitly display the flags (AMP) instead.

 What do you think?

**Comment by Grazfather** [comment]
Can we just suppress the chunk type when printing the fast bins? agreed that checking the neighbour's prev_inuse is the correct thing to do, I just think we should make it clear that it can be inaccurate for chunks of fastbin size.

**Comment by hugsy** [comment]
That sounds reasonable, and will make the display clearer. I'll do that later today and push it to `dev`.

**Comment by hugsy** [comment]
This issue is fixed `dev`, it will be closed when merged to `master`.
