### ISSUE TITLE
'gef missing' error

### ISSUE THREAD

**Issue by A1phaZer0** [hugsy/gef#177]
Hi,
```c
GDB: Ubuntu 7.11.1-0ubuntu1~16.04
Python: 3.5
GEF: master branch
```
I got this message:
```c
GEF for linux ready, type `gef' to start, `gef config' to configure
51 commands loaded for GDB 7.11.1 using Python engine 3.5
[*] 5 commands could not be loaded, run `gef missing` to know why.
Reading symbols from xor...(no debugging symbols found)...done.
gef➤  gef missing
[*] Command `ropper` is missing, reason  →  Missing `ropper` package for Python3, install with: `pip3 install ropper`.
[*] Command `unicorn-emulate` is missing, reason  →  Missing `capstone` package for Python3. Install with `pip3 install capstone`.
[*] Command `assemble` is missing, reason  →  Missing `keystone-engine` package for Python3, install with: `pip3 install keystone-engine`.
[*] Command `set-permission` is missing, reason  →  Missing `keystone-engine` package for Python3, install with: `pip3 install keystone-engine`.
[*] Command `capstone-disassemble` is missing, reason  →  Missing `capstone` package for Python3. Install with `pip3 install capstone`.
```
But, I've installed all packages already.
```c
$ pip3 install capstone
Requirement already satisfied: capstone in /home/ka9k/.local/lib/python3.5/site-packages
```

**Comment by A1phaZer0** [comment]
Distro related issues. 
Workaround: 
1. sudo apt-get install python-capstone
2. https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE-NIX.md
Case closed.

**Comment by hugsy** [comment]
FTR:
This is because `capstone` installed via `pip` failed to compile properly the C library. But there are issues in `keystone` and `capstone` as `pip` marks the package installed even if the compilation fails. An easy way to test is by running `python3 -c 'import capstone'` (which will fail). And this is why installing precompiled binaries (via `apt-get`) or compiling the lib yourself worked.

In any case, this is not a GEF issue but a packaging issue from `capstone` (also exist with `keystone` and `unicorn`).
