### ISSUE TITLE
add pie breakpoint support

### ISSUE THREAD

**Issue by Escapingbug** [hugsy/gef#183]
Hi. I found that gef has no pie support for now, do you have any plan to add that sometime? This is quite a large feature, I implemented one myself but it may not be very good for now.

I hope to have something like insert a PIE breakpoint and every time I start a program the breakpoint is set. According to my implementation, I used separate commands to do so, like these:
* pie breakpoint: set a pie breakpoint
* pie run: run a pie program, this is used instead of `run`, so it can correctly set a real breakpoint
* pie attach: attach a pie program, same as above, use this instead of `attach`
* pie remote: remote attach a pie program
* pie info: show pie breakpoints information
* pie delete: delete a pie breakpoint

I found that maybe this way of achieving this goal is not so elegant, so that I haven't done a pull request yet. How do you guys think about these?

**Comment by hugsy** [comment]
Hi there!

Not 100% to see what you mean by "PIE breakpoints", especially because of ASLR. gef currently supports PIE only for dynamically determining the most probable entrypoint (command `entry-break`). How would you know which address to break on? 

If you do have an implementation, please share it here, I'll be happy to take a look.

Cheers

**Comment by Escapingbug** [comment]
Thanks for replying. I'll send my pull request so you can read my code. But I haven't run a lot of tests, so it may contains many many many many bugs. Just a POC anyway. :)

**Comment by hugsy** [comment]
PR #184 was successfully merged, this issue can closed.
