### ISSUE TITLE
Add tty out option for each context type.

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#309]
Add a setting for each context type (that defaults to stdout) that allows you do choose an alternate file.

Probably safe to assume it's a tty.

```python
from contextlib import redirect_stdout

if <this context has a ttyout>
    with redirect_stdout(<thatttyout>):
        this_context()
```

**Comment by hugsy** [comment]
Like what we do here:
https://github.com/hugsy/gef/blob/c15643081064579ef375ccfc1c769f7d2c3a76a4/gef.py#L6710-L6712 ?

**Comment by Grazfather** [comment]
Yeah, but it would be nice if we could assign a few different outputs, and then assign parts of the context to it. Sort of like context.layout, but we could add extra context 'windows' and set a layout in each.

**Comment by hugsy** [comment]
In what scenario would be used ?

**Comment by hugsy** [comment]
I think `voltron` is much better suited for that. So far GEF and Voltron don't overlap in terms of features meaning that people can enjoy the best of both worlds (I actually know people in my CTF team that actually use such setup). 

If we start mixing things, it'll become confusing for everyone, hackish and hard to maintain. So I don't think we should implement this (especially since you just said even you won't be using it, there's no point adding unused code).

**Comment by Grazfather** [comment]
Fair enough

**Comment by bet4it** [comment]
You can have a try of [hyperpwn](https://github.com/bet4it/hyperpwn).
