### ISSUE TITLE
entry-break command when target is running

### ISSUE THREAD

**Issue by ttimasdf** [hugsy/gef#318]
Your issue will be closed unless you confirm the following:
  * [x] Did you use the latest version of GEF from `master` branch?
  * [x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x] Did you check [closed issues](https://github.com/hugsy/gef/issues)?

### Step 1: Describe your environment

  * Operating System: Ubuntu 18.04
  * Architecture: x86
  * GDB version (including the Python library version): 8.1.1 python 3.6

#### Steps to reproduce

  1. `qemu-aarch64 -g 1234 ./binary`
  2. In gef, attach, then `entry-break`.

#### Observed Results

Got error `gdb is already running`

#### Expected results

After commented out [this](https://github.com/hugsy/gef/blob/c15643081064579ef375ccfc1c769f7d2c3a76a4/gef.py#L6573).
break at entrypoint as expected

I know from its implementation, for this command to work, the program must be stopped before the entry point. I was wondering if it's better to have an option to let user to run `entry-break` forcefully when target is running, for attaching to remote will always be, start target first, then attach. And the command will never work. Better idea?

**Comment by hugsy** [comment]
Come to think of it, I think we can delete altogether the check at https://github.com/hugsy/gef/blob/c15643081064579ef375ccfc1c769f7d2c3a76a4/gef.py#L6571-L6573 simply because this command only adds a temporary breakpoint. Worst case (i.e. `$pc` is already past) the breakpoint won't get hit, big whoop since it'll be deleted at the next execution.

Thoughts @Grazfather ?
