### ISSUE TITLE
figure out CircleCI caching to speed up tests

### ISSUE THREAD

**Issue by Grazfather** [hugsy/gef#342]
Right now we re-install capstone, keystone, unicorn, plus all the python modules on every build.

Let's cache this to quicken it up.

**Comment by fibonascii** [comment]
Taking a look at this as I've worked with Circle in the past.

**Comment by fibonascii** [comment]
After doing some testing I think I've figured out the issue.

I went ahead and removed the checksum for the config.yaml in the pydeps line and and ran a couple builds. 
`- pydeps-{{ .Branch }}`

Here is a small sample of the output of restoring the cache

`tar: usr/local/lib/python3.4/site-packages/capstone/lib/libcapstone.so: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/mips.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/mips_const.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/ppc.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/ppc_const.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/sparc.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/sparc_const.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/systemz.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied
tar: usr/local/lib/python3.4/site-packages/capstone/sysz_const.py: Cannot open: No such file or directory
tar: usr/local/lib/python3.4/site-packages/capstone: Cannot mkdir: Permission denied`

The problem is that the packages are being installed with sudo and not being restored with an elevated user.

**Comment by fibonascii** [comment]
![screen shot 2018-10-23 at 11 27 57 pm](https://user-images.githubusercontent.com/11827510/47406334-5847f600-d71b-11e8-842d-b7f4b2938abf.png)
I've got it successfully restoring from cache using venv. The problem is that the tests are still failing 

![screen shot 2018-10-23 at 11 29 43 pm](https://user-images.githubusercontent.com/11827510/47406376-8e857580-d71b-11e8-822d-557663899fe7.png)

**Comment by fibonascii** [comment]
I was able to solve this issue by doing:
`chown -R circleci:circleci /usr/local/lib/python3.4/` right before the restore

**Comment by fibonascii** [comment]
PR Submitted: https://github.com/hugsy/gef/pull/367

**Comment by Grazfather** [comment]
The caching is working, but it's building from @fibonascii 's docker.

@hugsy: Can you set up docker cloud (and this repo) to build from the Dockerfile now present in this repo? Once that's done we can modify _circle.yml_ to point to that one instead.

**Comment by Grazfather** [comment]
No rush at all!

**Comment by hugsy** [comment]
FTR Done in https://hub.docker.com/r/crazyhugsy/gef/

**Comment by Grazfather** [comment]
🎉
