### ISSUE TITLE
Color may lead an display problem

### ISSUE THREAD

**Issue by windcarp** [hugsy/gef#41]
I'm using gnome-terminal .When using GEF, output of "colored text" display with "[0001] xxx [0001] ". I changed 
RED            = "\001\x1b[31m\002"
to
RED            = "\x1b[31m"
and solved the problem, hope an improvment will be made when you update it.

Finally, thanks for your works!

**Comment by hugsy** [comment]
Hi,

Thanks for the feedback. This change was introduced by #39 to make proper return line feed.

Apparently this issue is actually depending on which terminal is being used. I've tested this with xterm, roxterm, lxterminal and do not have the issue. I've just tested on gnome-terminal and I confirm your bug. I will revert the change.

**Comment by hugsy** [comment]
After a bit of Googling, I've solved the issue (working on all terms).

Please re-test and let me know if it works for you as well. 

Thanks.

**Comment by windcarp** [comment]
I've test it and it works well with gnome-terminal.

Thanks.

**Comment by hugsy** [comment]
Awesome :sunglasses: I've been meaning to fix that for quite some time
