### ISSUE TITLE
Conflicting aliases with peda

### ISSUE THREAD

**Issue by Inf0Junki3** [hugsy/gef#45]
Hello,

First of all, kudos! Great tools, loving it. Have been playing around with gef, and comparing some of the utilities it brings to gdb with peda's set. As you pointed out in your wiki, why *not* use peda as well?

I first set out to use *either* peda *or* gef. I imagine that's how you saw people using it. But then I thought, why not have them both in .gdbinit?

I noticed that there was some overlap in the aliases between the two. For instance, 'asm' aliases 'assemble' in gef, but 'asmsearch' in peda. ps and grep also have conflicts. After changing the aliases slightly in gef, I see that the two coexist and compliment each other nicely.

As a request, do you think it would be possible to change the aliases slightly so that the two can be loaded in gdb at the same time?

HTH,
IJ.

**Comment by hugsy** [comment]
Hi @Inf0Junki3 ,

Thank you for your feedback.
It seems to me that running both `peda` and `gef` at the same is a very bad idea at many levels, especially for the overlaps as you pointed out.

A few years ago, I would have agreed and would probably have changed the aliases so that `gef` can exist in parallel of `peda`. However, today, `gef` offers by far more features than `peda`, is cleaner (better GDB API support), and totally portable to any architecture that GDB supports.

So I do not see a point in modifying `gef` commands for that, as `gef` super-seeds `peda`.

If you can give me valid arguments, I can re-consider it.

Cheers,

**Comment by Inf0Junki3** [comment]
Hiya @hugsy,

Thanks for your response; mea culpa, I took a much closer look at gef / peda, and realized that the functionality that I thought was missing in gef was in fact renamed (searchmem -> search-pattern) / regrouped (pattern-search, pattern-create --> pattern). Clearly you've put a lot of thought into the renaming -- old habits die hard, I guess.

Cheers,
IJ.
