### ISSUE TITLE
Enable auto-completion with gef commands

### ISSUE THREAD

**Issue by xeyownt** [hugsy/gef#544]
Ok, so, "I'm always frustrated..." ;-) when using one of the gef commands, like `hexdump` or `memory watch`, the auto-completion with TAB does not work.

It would be nice if TAB would auto-complete source symbol whenever possible.
As a fallback, I would enable it everywhere, given that gef commands can in any case be aliased, whereas source code identifiers are just... a given in many situations.

Currently, because of lack of auto-completion, I often fallback to gdb built-in commands, or I end up using the mouse (brrr...)

Note: I can't tell whether it is a bug or a feature request. I found a completer bug (related to `ropper`), but not sure this is the same.

**Comment by hugsy** [comment]
Although bit rudely asked, @xeyownt was legit: root commands have automatically the flag `gdb.COMPLETE_LOCATION` set, but it is not inherited making sub-commands requiring to have it declared in their `__init__()`. 

So far, `hexdump`, `patch` and `memory` are done, but there might be other commands that need to be.

@xeyownt word of advice: we (the devs) are maintaining gef on our own spare time, for free. Adding some basic courtesy (like starting with "Hi", ending with a "Thank you"), goes a long way, and descent explanation (instead of useless personal complaints) are useful. If there are templates for bug reports/feature requests, use them. Normally I'd just close such ticket.

**Comment by xeyownt** [comment]
Hello,

I guess it is a matter of taste because in my case I usually prefer short messages without much overhead. Putting "Hi" and "Thank you" seems just like childish in a ticket system. Btw, did I pay anything to use your stuff? No. Do I have a brain? Yes. So "thank you" seems like granted.

If you want people to say "Hi" and "Thank you", what about **adding these to your template**, which I copied to the letter? Oh, mind you, I added a smiley. Maybe I should add one to every word?

Next time I'll think about filing an issue. I'll refrain. Next time I'll submit a patch (which I did already btw), I'll keep it for myself. Maybe you should do the same?

Now, bye and close.
