### ISSUE TITLE
Show arguments passed to a function

### ISSUE THREAD

**Issue by rick2600** [hugsy/gef#56]
Show arguments passed to a function in the `context_code` when hitting a call instruction.

**Comment by Grazfather** [comment]
So this could be done. Ideally it'd handle syscalls (which would require a `is_syscall` for each arch) as well as knowledge of the ABI. Assuming Linux for everything this isn't too bad.

**Comment by Grazfather** [comment]
Making progress

<img width="716" alt="" src="https://cloud.githubusercontent.com/assets/497310/22135711/cbbef688-de84-11e6-8b1b-796dc89ac0a1.png">

**Comment by Grazfather** [comment]
<img width="713" alt="x86" src="https://cloud.githubusercontent.com/assets/497310/22135851/b437eece-de85-11e6-856a-5bbc6c837475.png">

**Comment by Grazfather** [comment]
ARM
<img width="716" alt="ARM" src="https://cloud.githubusercontent.com/assets/497310/22135994/7fa0e9d0-de86-11e6-842b-69405d4a228c.png">

**Comment by Grazfather** [comment]
See Grazfather/gef@print_args

**Comment by glen-mac** [comment]
Would be great if it could be as accurate as PEDA is.

**Comment by hugsy** [comment]
@glen-mac PEDA uses ugly regexp that on top of being bad Python coding is meant 100% for x86. GEF tries to approach things more elegantly and in an architecture-agnostic way.

**Comment by hugsy** [comment]
@rick2600 : this topic is not dead, feel free to contact @Grazfather who's been working a lot on it if you want to beta-test :smile:

**Comment by hugsy** [comment]
@Grazfather Can you tell me where are you on that? I don't mind taking over because it's a useful feature. Should I start again from scratch ?

**Comment by Grazfather** [comment]
I scrapped my code because it was done naively.

I've seen implementations that recognize library functions and use the signature to determine the type and number of arguments. That could be cool (but heavy).

I've seen implementations that go back a few instructions to see if the args were written to recently. This is imperfect but pretty nice.

My naive solution just did something like 5 args always.

You have a preference?

**Comment by hugsy** [comment]
I was actually thinking of a compromise between the two approachs here since I happen (as I image a lot of others) to work on bins fully stripped so we can rely on signatures only.

What do you say of something like:

 1. if we have a signature then GEF displays explicit arguments, for instance:
```
call mempy
-----------------------
Arguments:
void *dest -> 0x<value>
const void *src -> 0x<value>
size_t n -> 0x<value>
```
(that should be fairly simple using [GDB symbols](https://sourceware.org/gdb/current/onlinedocs/gdb/Symbols-In-Python.html))

2. And if we don't have the signature, just disass up until the beginning of current block and show the arguments as guessed, if the argument register is being written to:
```
<beginning of block>
mov $rdi, 0x1337
call foobar
-----------------------
Guessed arguments:
$rdi -> 0x<value>
```

Does that sound realistic to change from your approach to that?

**Comment by hugsy** [comment]
@rick2600 @Grazfather 

I was really bored this wweekend so I implemented the approach I mentioned above. It is surprisingly small (~100 loc) and works everywhere (tested x86, ARM, AARCH64 and MIPS). 

If the symbols are defined, then it will display the arguments accurately, otherwise will show them as guessed.
With symbols:
![](https://i.imgur.com/X8pErfD.png)

Without:
![](https://i.imgur.com/pmOONhA.png)
And it is relatively accurate (all things considered).

It's available here: https://github.com/hugsy/gef-scripts/blob/master/context-args.py from now, to have enough time to test it correctly (requires to use the `dev` branch of GEF), so feel free to play with it and report the bugs. 

Once reliable enough, it'll land to `dev` then `master`.

Cheers

**Comment by Grazfather** [comment]
Well stop showing off ;)

I'll test it out this week!

**Comment by hugsy** [comment]
:sunglasses: 

I am actually super happy I have finally some time to work on gef again...

**Comment by hugsy** [comment]
Hey @rick2600 @Grazfather 

I've been testing this on challenges, and it works well enough (IMO) to be merged to `master`. Did you have a chance to test it too? I'm curious for more feedback.

Since it's a pretty cool change that I think people might be interested in having, I may also create a new release for it.

Cheers.

**Comment by hugsy** [comment]
Reported by @rick2600 , might not be easy to fix:

```
─────────────────────────────── Exception raised ───────────────────────────────
TypeError: Type is not a structure, union, or enum type.
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/vagrant/gef/gef.py", line 6614, in print_arguments_from_symbol()
    →     for i, f in enumerate(symbol.type.fields()):
↳ File "/home/vagrant/gef/gef.py", line 6593, in context_args()
    →     self.print_arguments_from_symbol(target, sym)
↳ File "/home/vagrant/gef/gef.py", line 6389, in do_invoke()
    →     self.layout_mapping[section]()
↳ File "/home/vagrant/gef/gef.py", line 2006, in wrapper()
    →     return f(*args, **kwargs)
↳ File "/home/vagrant/gef/gef.py", line 3359, in invoke()
    →     self.do_invoke(argv)
───────────────────────────── Last 10 GDB commands ─────────────────────────────
   18  gef save
   19  gef config gef.extra_plugins_dir ~/gef-extras/scripts
   20  gef save
   21  gef config 
   22  start
   23  ni
   24  start
   25  ni
   26  gef config gef.debug 1
   27  ctx
───────────────────────────── Runtime environment ──────────────────────────────
* GDB: 7.7.1
* Python: 3.4.3 - final
* OS: Linux - 3.13.0-143-generic (64bit) on Ubuntu 14.04 trusty
────────────────────────────────────────────────────────────────────────────────
```

**Comment by hugsy** [comment]
Actually I was wrong, it was easy to patch since GDB doesn't expose the function arguments to the Python interface before GDB 7.11.There's nothing we can do from GEF.

There is no choice but to rely on guessed arguments for that.

Thanks for the notice @rick2600

**Comment by hugsy** [comment]
So 2 CTF, many small challenges and test binaries after, I feel that the feature is pretty solid.
I did some good tests on ARM and AARCH64 (made a lot faster thanks to @Grazfather [amazing patch](https://github.com/hugsy/gef/pull/228/commits/9abe546b4b91cab6f785c6bd34307be7a60d578c)) and the "arguments from symbols" worked flawlessly. There's room for improvement on the guessed arguments, but again, since it's guessed, I don't feel too bad if it's not perfect.

So closing the ticket (after so long!), thanks all!
