### ISSUE TITLE
Code refactoring plan for release 2022.01 - GDB 8/Python 3.6)

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#767]
Todo list:
 - [x] #772
   - @hugsy 
 - [x] move **all** (non constant) globals under the `gef` namespace - @hugsy
 - [x] adjust existing classes to leverage python mechanism - like arenas through iterators etc. @hugsy 
 - [x] add 3.6 compatible type hints - @theguy147 
   - https://github.com/hugsy/gef/pull/774 
 - [x] switch to f-strings - @theguy147 
   - https://github.com/hugsy/gef/pull/768
 - [x] deprecate some old APIs - @hugsy 
 - [x] #776
   - @hugsy 
 - [x] separate the MachO stuff to `gef-extras/os/` - @hugsy 
   - hugsy/gef-extras@0eb3ba4acd7d93f27e3382a7e7d7c99715d0328c
   - hugsy/gef@43a9920db11b8b5c9a5456da902e17b88c7ea62b
 - [x] #775
   - @hugsy 

If you take a task, just add your handle next to the task(s)

**Comment by theguy147** [comment]
Since Python 3.3 the following errors where merged into `OSError` and are now just aliases:
- `EnvironmentError`
- `IOError`
- `WindowsError`
- `socket.error`
- `select.error`
- `mmap.error`

I found at least some occurrences of `EnvironmentError` and `socket.error` in the codebase. Should they also be refactored to use `OSError` or not?

**Comment by theguy147** [comment]
f-strings PR is ready at #768

**Comment by theguy147** [comment]
PR for updating generator and comprehension syntax is ready at #771

**Comment by theguy147** [comment]
one thing that would save a few bytes as well is that the file mode "r" (read) is the default for `open` (I think since PEP 3116/Python 3.0) and could be omitted. This could be done in 9 places in GEF and could thereby save 9*5=45 Bytes ;)
