### ISSUE TITLE
Feasibility suggestions

### ISSUE THREAD

**Issue by beef9999** [hugsy/gef#882]
### Type of feature request

Misc

### Summary Description

1. The source panel: Source file and line number shouldn't be collapsed. We all have wide screens nowadays. For example, `source:/root/rocksdb/b[...].h+435`.
2. The trace panel: Source file and line number should be able to configure to display. Otherwise we have to use `frame` to see the actual source code step by step.

### Implementation idea/suggestion

.

**Comment by Grazfather** [comment]
We need to collapse it if it is too long to fit on one line, but I agree that we shouldn't collapse it unless we need to. We can probably have the `title` function do the collapsing, though it would not know _how_ to collapse it nicely. Maybe `context_source` should use `self.tty_columns` instead of hardcoding 20 as the max fn length.

**Comment by beef9999** [comment]
Notify me if you have fixed it.

**Comment by hugsy** [comment]
> Notify me if you have fixed it.

This is a low priority for us. If you want to see this feature happening, we welcome a PR.

**Comment by beef9999** [comment]
You didn't even realize this is a major reason new users say good bye to you tool :-)

**Comment by theguy147** [comment]
@beef9999 This is an open source project where everyone chips in on their free time. If this is an issue you absolutely want to see in GEF than you're always welcome to create a PR with your changes instead of demanding other peoples to fix it even when they deem that the issue doesn't have a high priority for them.

While I agree that this issue doesn't qualify for high priority (for my use cases), we could actually prioritize the final part of the path instead of the beginning with something as simple as this change...

```diff
    def context_source(self) -> None:
        # ... snipped ...
        if len(fn) > 20:
-            fn = f"{fn[:15]}[...]{os.path.splitext(fn)[1]}"
+            fn = fn[-20:]
        # ... snipped ...
```

Allthough with really long filenames this could make things more confusing. A more (and maybe unnecessarily) complex approach would split the path into `dirname` and `basename` and start by shortening the `dirname`  in the front and if that doesn't suffice then continue to shorten the `basename` at the end...

Additionally, in the long run we could introduce a setting `context.line_length` (or similar) instead of all the hardcoded values in the codebase.

**Comment by beef9999** [comment]
I think a common problem among engineers is to equate priority with difficulty or functional complexity, while ignoring the basic fact that many users only use 30% of a product's basic functionality. For example, as a C++ application developer, I basically don't watch registers and assembly. The reason why I don't like gdb is that it doesn't have a color display like gef, and it can't print local variables conveniently. Maybe you would think these are simple usages that gef has been supported for a long time, but if it is not good enough or even flawed, most ordinary users will still go back to gdb.

**Comment by Grazfather** [comment]
I suggest you use gdb-dashboard instead of GEF.
