### ISSUE TITLE
[heap] main_arena symbol can never be found on 32bits binary compiled on x64-64

### ISSUE THREAD

**Issue by Young-X** [hugsy/gef#91]
I run the command "heap bins fast", and it returns 
"
[*] Failed to get `main_arena` symbol. heap commands may not work properly
[!] Invalid Glibc arena
"

Anyone can help me, please?

**Comment by hugsy** [comment]
This means that the symbol `main_arena` (mandatory when you use the [Glibc heap allocator](http://osxr.org:8080/glibc/source/malloc/malloc.c#1741)) cannot be found. This can be due to:
  * the fact that your binary is statically compiled, and no heap is needed
  * or you're using a different/custom heap allocator which is not supported.

Please note that the GitHub issue section is to be used to report bugs and issues, not a place to ask for help. Use the IRC [`freenode##gef`](https://webchat.freenode.net/?channels=##gef) for that. 

Closing the ticket.

**Comment by hugsy** [comment]
### Re-test

| Arch | Result |
|----|------|
| x64 native | :heavy_check_mark: |
| x86 compiled on x64 (`-m32`) | :heavy_multiplication_x:  |
| arm | :heavy_check_mark: |
| mips | :heavy_check_mark: |

Todo: investigate

**Comment by hugsy** [comment]
glibc/malloc/malloc.c
```c
static struct malloc_state main_arena =
{
  .mutex = _LIBC_LOCK_INITIALIZER,
  .next = &main_arena,
  .attached_threads = 1
};
```

`main_arena` is static, so the symbol can only be found by GDB when the debug symbol are added. So to solve this, `apt install libc6-dbg:arch`.
