### ISSUE TITLE
[Bug] pthread tcache bins do not display with patched libc

### ISSUE THREAD

**Issue by robwaz** [hugsy/gef#939]
### GEF+GDB version

```shell
gef➤  version
GEF: rev:95903054044326df72e77a7128bac100505c831f (Git - clean)
SHA256(/opt/gef/gef.py): 8ccbf334222d3c1bd2cf66cddb3a131c69f0acfa7efd7f48edd43d7422b42b96
GDB: 9.2
GDB-Python: 3.8

Issue also occurs on dev HEAD
```

### Operating System

Ubuntu 20.04

### Describe the issue you encountered

GEF does not display thread tcache bins with the command `heap bins tcache all` on binary with patched libc/ld.

The binary above does compile and display correctly when compiled.  However when patching the binary with `patchelf` to a newer libc and ld version, all cache bins will display empty.  `pwndbg` does display the correct tcache information in this scenario, so I believe it to be a GEF specific bug.  Issue is related, but not the same as #934, as I find in the single-threaded case tcache bins are correctly displayed with safe-linking enabled.

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

Binaries (including modified linked libraries) included.

```
gcc -pthread ex.c -o b.out
patchelf --replace-needed libpthread.so.0 ./ex/libpthread.so.0 b.out
patchelf --replace-needed libc.so.6 ./ex/libc.so.6 b.out
patchelf --set-interpreter ./ex/ld-linux-x86-64.so.2 b.out

gdb ./b.out
GEF>run
^c
GEF>heap bins tcache all
```

### Minimalist test case

Minimal example program:
```
#include <pthread.h>
#include <unistd.h>


void func() {
  char *ptr = malloc(0x400);
  char *ptr2 = malloc(0x400);
  free(ptr);
  free(ptr2);
  puts("sleeping for 300 sec");
  sleep(300);
  puts("thread exiting");
}

int main(int argc, char *argv) {
        pthread_attr_t attr;
        pthread_t thread;
        pthread_attr_init(&attr);
        pthread_create(&thread, &attr, func, NULL);

        puts("waiting on thread");
        pthread_join(thread, NULL);
        puts("main thread exiting");
}
```

### Additional context?

[ex.zip](https://github.com/hugsy/gef/files/11045241/ex.zip)

**Comment by theguy147** [comment]
I had a look and I can reproduce this issue with your program and the provided (stripped) libs. 

My guess would be (and that is how it was for me) that on your machine you have the debug symbols available for your regular system-wide libc and libptread, but you do not have debug symbols available for the provided challenge libs.

Although GEF tries to manage without symbols (and e.g. the `main_arena` can be easily brute-forced with the `gef.bruteforce_main_arena` setting), it seems like we have neglected the tcache.

The issue is in `GlibcHeapTcachebinsCommand.find_tcache()`: At the time when the code was written the assumption was that if the `tcache` symbol is not available, then the binary was not linked against libpthread and therefore there can only be one thread. With the available symbols the `try` branch will execute fine and each threads tcache can easily be found. If however, there are no debug symbols then the `except` branch will always return the tcache for the very first thread (the thread with the empty tcache).

The quickest fix for you would be to use the debug symbols for your challenge libs if you can get them. For a more permanent fix we will have to come up with a way to correctly calculate the tcache addresses for each thread even without symbols and at least I couldn't think of anything on the spot...


 As such the calculations in the `except` branch only works for the very first thread.

Somehow this has gone unnoticed until now.

**Comment by theguy147** [comment]
I took a look at pwndbgs implementation for this issue (when stuck without symbols) and they look for the tcache addresses in the TLS and if that fails they assume the struct to be in the first chunk of the threads arenas heap. Although this assumption succeeds in your concrete example, this would not fix the underlying issue...
