### ISSUE TITLE
[Bug] gef is slow while debugging kernel in qemu

### ISSUE THREAD

**Issue by karzanWang** [hugsy/gef#978]
### GEF+GDB version

```shell
gef: 2023.04 release
gdb: GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
```

### Operating System

Ubuntu 22.04.2 LTS

### Describe the issue you encountered

Gdb with gef is slow when debugging kernel in qemu (with command gef-remote --qemu-user --qemu-binary ./vmlinux localhost 1234). 

### Do you read the docs and look at previously closed issues/PRs for similar cases?

Yes

### Architecture impacted

- [ ] X86
- [X] X64
- [ ] ARM
- [ ] ARM64
- [ ] MIPS
- [ ] MIPS64
- [ ] PPC
- [ ] PPC64
- [ ] RISCV

### Describe your issue. Without a proper reproduction step-by-step, your issue will be ignored.

1. downlaod the challenge (https://github.com/Crusaders-of-Rust/corCTF-2022-public-challenge-archive/tree/master/pwn/cache-of-castaways)
2. extract the vmlinux elf from bzImage.
3. start the kernel with qemu with the `run` script. (and add `-s` in qemu args)
4. start gdb, execute `gef-remote --qemu-user --qemu-binary ./vmlinux localhost 1234`
5. normally debug the kernel, execute sth. like `si`. This is slow.

**Comment by hugsy** [comment]
Not quite sure what you mean by "slow": I tried it and it is as fast as what you can expect from debugging an emulated VM. If you're referring to the slow-down when displaying the `context` pane, it is indeed slowed down, but that's mostly caused by the multiple pointer dereferencing. So you can speed things by making the context collect less info by editing your view (`gef config context.layout`). In addition, it is well-known that the gdb remote protocol is old and slow. 

So unless you can give us better tracks as to which specific part(s) we can improve (in GEF), there's not a lot we can do.
